var tag = [
  {
	"tagPage": 0,
    "tagName": "冠、亚军和",
    "playTypeM": [65],
    "straight": [],
    "playCodeM": "Mix",
  },
  {
	"tagPage": 1,
    "tagName": "冠軍",
    "playTypeM": [66, 16],
    "straight": [],
    "posContent": [0],
    "playCodeM": "One",
  },
  {
	"tagPage": 2,
    "tagName": "亚軍",
    "playTypeM": [67, 16],
    "straight": [],
    "posContent": [1],
    "playCodeM": "Two",
  },
  {
	"tagPage": 1,
    "tagName": "第三名",
    "playTypeM": [68, 16],
    "straight": [],
    "posContent": [2],
    "playCodeM": "Three",
  },
  {
	"tagPage": 1,
    "tagName": "第四名",
    "playTypeM": [69, 16],
    "straight": [],
    "posContent": [3],
    "playCodeM": "Four",
  },
  {
	"tagPage": 1,
    "tagName": "第五名",
    "playTypeM": [70, 16],
    "straight": [],
    "posContent": [4],
    "playCodeM": "Five",
  },
  {
	"tagPage": 1,
    "tagName": "第六名",
    "playTypeM": [71, 16],
    "straight": [],
    "posContent": [5],
    "playCodeM": "Six",
  },
  {
	"tagPage": 1,
    "tagName": "第七名",
    "playTypeM": [72, 16],
    "straight": [],
    "posContent": [6],
    "playCodeM": "Seven",
  },
  {
	"tagPage": 1,
    "tagName": "第八名",
    "playTypeM": [73, 16],
    "straight": [],
    "posContent": [7],
    "playCodeM": "Eight",
  },
  {
	"tagPage": 1,
    "tagName": "第九名",
    "playTypeM": [74, 16],
    "straight": [],
    "posContent": [8],
    "playCodeM": "Night",
  },
  {
	"tagPage": 1,
    "tagName": "第十名",
    "playTypeM": [75, 16],
    "straight": [],
    "posContent": [9],
    "playCodeM": "Ten",
  }
  
]